#!/usr/bin/env python3

from argparse import ArgumentParser

from chem_translate import translate


def main():
    parser = ArgumentParser(description="Translate a chemical equation to a different format.")
    parser.add_argument(
        "input",
        metavar="I",
        help="Equation to be formatted or file to be read from",
    )
    parser.add_argument(
        "-f",
        "--file",
        default=False,
        action="store_true",
        help="Read from a file [%(default)s]",
    )

    args = parser.parse_args()

    if args.file:
        with open(args.input) as f:
            equations = f.readlines()
    else:
        equations = [args.input]

    print("Chemical Equation")
    for equation in equations:
        print(translate(equation, args.format))
